repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-merge-conflict

-   repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
    -   id: nbstripout
